export const TOP_NAVI_HEIGHT = 'top_navi_height'
export const BOTTOM_AVOID_AREA_HEIGHT = 'bottom_avoid_area_height'
export const BW_PREFERENCES_NAME = 'bw_preferences_name'
export const HAS_GUIDE = 'has_guide'
export const HAS_PRIVACY = 'has_privacy'
export const HAS_SELECT_THEME = 'has_select_theme'
export const SCREEN_WIDTH = 'screen_width'
export const SCREEN_HEIGHT = 'screen_height'
export const UUID_STRING = 'uuid_string'
export const CURRENT_THEME_ID = 'current_theme_id'






export const DEFAULT_THEME_ID = '124'
export const HOME_PAGE_SHOW_EVENT_ID = 1
export const THEME_BG_UPDATE = 2