export const TOP_NAVI_HEIGHT = 'top_navi_height'
export const BOTTOM_AVOID_AREA_HEIGHT = 'bottom_avoid_area_height'
export const BW_PREFERENCES_NAME = 'bw_preferences_name'
export const HAS_GUIDE = 'has_guide'
export const HAS_PRIVACY = 'has_privacy'
export const HAS_SELECT_THEME = 'has_select_theme'
export const SCREEN_WIDTH = 'screen_width'
export const SCREEN_HEIGHT = 'screen_height'
export const UUID_STRING = 'uuid_string'
export const CURRENT_THEME_ID = 'current_theme_id'
export const CURRENT_THEME_TYPE = 'current_theme_type' // 1经典 2简洁
export const LONGITUDE = 'longitude'
export const LATITUDE = 'latitude'




export const DEFAULT_THEME_ID = '124'
export const DEFAULT_THEME_TYPE = 1

export const ADD_CITY_EVENT_ID = 1
export const CHANGE_THEME_EVENT_ID = 2